server:
  port: 8081

# spring actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, loggers
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    loggers:
      enabled: true