spring:
  application:
    name: rating
  config:
    activate:
      on-profile: azure

# multi datasource 설정
app:
  datasource:
    client:
      jdbc-url: jdbc:postgresql://c.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432/citus
#      jdbc-url: jdbc:postgresql://localhost:5432/bmtdb
      username: bmtstat3
#      username: postgres
      password: djqjdlskf12!
#      password: password
      driver-class-name: org.postgresql.Driver