#logging:
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
##  level:
##    org.springframework.web: DEBUG
##    guru.springframework.controllers: DEBUG
##    org.hibernate: DEBUG
#  file:
#    name: logs/dev_profile_app.log

#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql:aurora://database-1.cluster-cehtr4vjq6c5.ap-northeast-2.rds.amazonaws.com:3306
#      username: admin
#      password: ans159357!
#      driver-class-name: org.mariadb.jdbc.Driver

app:
  datasource:
    main:
      jdbc-url: jdbc:mariadb://localhost:3306/test?useSSL=false
      username: root
      password: password
    clienta:
      jdbc-url: jdbc:mariadb://localhost:3308/test?useSSL=false
      username: root
      password: password