spring:
  application:
    name: rating
  config:
    activate:
      on-profile: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?useSSL=false
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: true
#    show-sql: true
#    open-in-view: false

# multi datasource 설정
app:
  datasource:
    client0:
      jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    client1:
      jdbc-url: jdbc:mysql://localhost:3308/test?useSSL=false
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
#    client2:
#      jdbc-url: jdbc:mariadb://localhost:3308/test?useSSL=false
#      username: root
#      password: password
#      driver-class-name: org.mariadb.jdbc.Driver
#    client3:
#      jdbc-url: jdbc:mariadb://localhost:3308/test?useSSL=false
#      username: root
#      password: password
#      driver-class-name: org.mariadb.jdbc.Driver
#    client4:
#      jdbc-url: jdbc:mariadb://localhost:3308/test?useSSL=false
#      username: root
#      password: password
#      driver-class-name: org.mariadb.jdbc.Driver
#    client5:
#      jdbc-url: jdbc:mariadb://localhost:3308/test?useSSL=false
#      username: root
#      password: password
#      driver-class-name: org.mariadb.jdbc.Driver
#    client6:
#      jdbc-url: jdbc:mariadb://localhost:3308/test?useSSL=false
#      username: root
#      password: password
#      driver-class-name: org.mariadb.jdbc.Driver
#    client7:
#      jdbc-url: jdbc:mariadb://localhost:3308/test?useSSL=false
#      username: root
#      password: password
#      driver-class-name: org.mariadb.jdbc.Driver
#    client8:
#      jdbc-url: jdbc:mariadb://localhost:3308/test?useSSL=false
#      username: root
#      password: password
#      driver-class-name: org.mariadb.jdbc.Driver
#    client9:
#      jdbc-url: jdbc:mariadb://localhost:3308/test?useSSL=false
#      username: root
#      password: password
#      driver-class-name: org.mariadb.jdbc.Driver