spring:
  application:
    name: rating
  config:
    activate:
      on-profile: azure

# multi datasource 설정
app:
  datasource:
    client:
      jdbc-url: jdbc:postgresql://w0.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w1.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w2.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w3.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w4.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w5.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w6.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w7.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w8.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w9.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w10.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w11.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w12.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w13.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w14.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w15.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w16.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w17.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w18.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w19.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w20.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w21.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w22.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w23.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w24.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w25.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w26.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w27.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w28.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w29.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w30.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w31.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w32.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w33.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w34.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w35.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w36.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w37.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w38.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w39.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w40.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w41.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w42.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w43.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w44.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w45.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w46.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w47.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w48.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w49.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w50.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w51.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w52.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w53.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w54.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w55.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w56.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w57.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w58.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w59.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w60.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w61.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w62.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w63.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w64.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w65.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w66.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w67.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w68.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w69.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w70.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w71.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w72.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w73.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w74.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w75.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w76.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w77.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w78.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432,\
        w79.bss-bmt-kc-urt-postgresql.postgres.database.azure.com:5432
#      jdbc-url: jdbc:postgresql://localhost:5432/bmtdb
      username: bmtstat3
#      username: postgres
      password: djqjdlskf12!
#      password: password
      driver-class-name: org.postgresql.Driver